api/urls.py
from django.urls import path
from . views import ListCustomUsersApiView, ListEquipmentApiView, CreateCustomUserApiView, ListPlanApiView, ListUserPlanApiView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('register', CreateCustomUserApiView.as_view(), name='signup'),
    path('login', TokenObtainPairView.as_view(), name='signin'),
    path('refresh', TokenRefreshView.as_view(), name='refresh'),
    path('plans', ListPlanApiView.as_view(), name='list-plans'),
    path('users', ListCustomUsersApiView.as_view(), name='list-users'),
    path('equipments', ListEquipmentApiView.as_view(), name='list-equipments'),
    path('subscriptions', ListUserPlanApiView.as_view(), name='list-subscriptions'),
    
]

core/urls.py
from django.urls import path, include
from . views import ListCustomUsers, ListPlan, ListEquipment, ListSubscriptions, SubscriptionDetail


urlpatterns = [
    path('plans', ListPlan.as_view(), name='list-plans'),
    path('users', ListCustomUsers.as_view(), name='list-users'),
    path('equipments', ListEquipment.as_view(), name='list-equipments'),
    path('subscriptions', ListSubscriptions.as_view(), name='list-subscriptions'),
    path('subscriptions/<int:pk>', SubscriptionDetail.as_view(), name='subscription-detail'),
    
]

gym_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from gym_management_system import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('admin/', admin.site.urls),
    path('core/', include(('core.urls', 'core'), namespace='core')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from gym_management_system.settings import AUTH_USER_MODEL


BILLING_DURATION_CHOICES = (
    ("MONTHLY", "Monthly"),
    ("QUARTERLY", "Quarterly"),
    ("HALF YEARLY", "Half Yearly"),
    ("YEARLY", "Yearly"),
)


class CustomUserManager(BaseUserManager):
    def create_superuser(self, email, password):
        user = self.model(email=email)
        user.set_password(password)
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField("Email", unique=True, max_length=255, blank=True, null=True)
    username = models.CharField("User Name", unique=True, max_length=255, blank=True, null=True)
    profile_image = models.FileField(upload_to='profile_image', blank=True, null=True)
    is_active = models.BooleanField('Active', default=True)
    is_staff = models.BooleanField('Staff', default=False)
    is_superuser = models.BooleanField('Super User', default=False)
    objects = CustomUserManager()
    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

    class Meta:
        '''Doc string for meta'''
        verbose_name_plural = "User"



class Plan(models.Model):
    name = models.CharField(max_length=255)
    fees = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=2, decimal_places=2)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    billing_duration = models.CharField("Billing Duration", max_length=50, choices=BILLING_DURATION_CHOICES, null=True, blank=True)
    image = models.ImageField(upload_to='plan_images')
    

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name_plural = "Plan"


class UserPlan(models.Model):
    user_id = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    plan_id = models.ForeignKey(Plan, on_delete=models.CASCADE)
    subscription_date = models.DateField()
    is_paid = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return '(%s, %s)' % (self.user_id.email, self.plan_id.name)

    class Meta:
        verbose_name_plural = "User Subscription Plans"


class Equipment(models.Model):
    name = models.CharField(max_length=255)
    per_unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='equipment_images')
    

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name_plural = "Equipment"

api/views.py
from rest_framework.generics import ListAPIView, CreateAPIView
from . serializers import ListCustomUserSerializer, CustomUserSerializer, PlanSerializer, UserPlanSerializer, EquipmentSerializer \
    , CustomTokenObtainPairSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.views import TokenObtainPairView
from core.models import CustomUser, Plan, UserPlan, Equipment


class CreateCustomUserApiView(CreateAPIView):
    serializer_class = CustomUserSerializer
    queryset = CustomUser.objects.all()

class CustomTokenObtainPairView(TokenObtainPairView):
    # Replace the serializer with your custom
    serializer_class = CustomTokenObtainPairSerializer


class ListCustomUsersApiView(ListAPIView):
    serializer_class = ListCustomUserSerializer
    queryset = CustomUser.objects.all()


class ListEquipmentApiView(ListAPIView):
    serializer_class = EquipmentSerializer
    queryset = Equipment.objects.all()
    permission_classes = [IsAuthenticated]


class ListUserPlanApiView(ListAPIView):
    serializer_class = UserPlanSerializer
    queryset = UserPlan.objects.all()


class ListPlanApiView(ListAPIView):
    serializer_class = PlanSerializer
    queryset = Plan.objects.all()

core/views.py
from django.views.generic import ListView, DetailView
from .models import CustomUser, Equipment, UserPlan, Plan
from django.contrib.auth.mixins import LoginRequiredMixin


class ListCustomUsers(ListView):
    """A View to list all the users"""

    model = CustomUser
    template_name = 'core/list_user.html'
    context_object_name = 'users'

    def get_queryset(self):
        qs = CustomUser.objects.all().exclude(is_superuser=True)
        return qs


class ListPlan(ListView):
    """A View to list all the plans"""

    model = Plan
    template_name = 'core/list_plan.html'
    context_object_name = 'plans'

    def get_queryset(self):
        qs = Plan.objects.all()
        return qs


class ListEquipment(ListView):
    """A View to list all the equipments"""

    model = Equipment
    template_name = 'core/list_equipment.html'
    context_object_name = 'equipments'

    def get_queryset(self):
        qs = Equipment.objects.all()
        return qs


class ListSubscriptions(ListView):
    """A View to list all the subscriptions"""

    model = UserPlan
    template_name = 'core/list_user_plan.html'
    context_object_name = 'subscriptions'

    def get_queryset(self):
        if self.request.GET.get('search-input'):
            userEmail = self.request.GET.get('search-input')
            qs = UserPlan.objects.filter(user_id__email__icontains=userEmail).order_by('-subscription_date')
        else:
            qs = UserPlan.objects.all().order_by('-subscription_date')
        return qs


class SubscriptionDetail(DetailView):
    """A View to get detail of a subscription"""

    model = UserPlan
    template_name = 'core/user_plan_detail.html'
    context_object_name = 'subscription'

templates/core/list_equipment.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %} GymManagement System - Equipments {% endblock %}
{% block content %}
{%include 'partials/header.html' %}

<div class="blue lighten-5">
    <div class="section">
        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12">
                <div class="icon-block">
                    <h2 class="center brown-text">
                        <i class="material-icons">settings</i>
                    </h2>
                    <h5 class="center">World Class Equipments</h5>

                    {% for each_equipment in equipments %}
                    <div class="col s12 m6">
                        <div class="card">
                          <div class="card-image">
                            <img src="{{ each_equipment.image.url }}">
                            <span class="card-title">{{ each_equipment.name }}</span>
                          </div>
                          <div class="card-content">
                            <p>Available Quantity - {{ each_equipment.quantity }}</p>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'partials/footer.html' %} {% endblock %}

templates/core/list_plan.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %} GymManagement System - Plans {% endblock %}
{% block content %}
{%include 'partials/header.html' %}

<div class="blue lighten-5">
    <div class="section">
        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12">
                <div class="icon-block">
                    <h2 class="center brown-text">
                        <i class="material-icons">grade</i>
                    </h2>
                    <h5 class="center">Plans</h5>

                    {% for each_plan in plans %}
                    <div class="col s12 m6">
                        <div class="card">
                          <div class="card-image">
                            <img src="{{ each_plan.image.url }}">
                            <span class="card-title">{{ each_plan.name }}</span>
                          </div>
                          <div class="card-content">
                            <p>{{ each_plan.description }}</p>
                          </div>
                          <div class="card-action">
                            <p>FEES - {{ each_plan.fees }}</p>
                            <p>Billed {{ each_plan.billing_duration }}</p>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'partials/footer.html' %} {% endblock %}

templates/core/list_user.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %} GymManagement System - Users {% endblock %}
{% block content %}
{%include 'partials/header.html' %}

<div class="blue lighten-5">
    <div class="section">
        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12">
                <div class="icon-block">
                    <h2 class="center brown-text">
                        <i class="material-icons">person</i>
                    </h2>
                    <h5 class="center">Members</h5>

                    {% for each_user in users %}
                    <div class="col s12 m6">
                        <div class="card">
                          <div class="card-image">
                            <img src="{{ each_user.profile_image.url }}">
                            <span class="card-title">{{ each_user.username }}</span>
                          </div>
                          <div class="card-content">
                            <p>Email of the user - {{ each_user.email }}</p>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'partials/footer.html' %} {% endblock %}

templates/core/list_user_plan.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %} GymManagement System - Equipments {% endblock %}
{% block content %}
{%include 'partials/header.html' %}

<div class="blue lighten-5">
    <div class="section">
        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12">
                <div class="icon-block">
                    <h2 class="center brown-text">
                        <i class="material-icons">bolt</i>
                    </h2>
                    <h5 class="center">Subscriptions</h5>
                    <form action="{% url 'core:list-subscriptions' %}" class="col s12" method="GET">
                        <div class="row">
                            <h5 class="col s2">Search Users</h5>
                            <div class="input-field col s8">
                                <input class="white grey-text autocomplete" placeholder="Aruba, Cancun, etc..." type="text" name="search-input" id="autocomplete-input">
                            </div>
                            <div class="input-field col s2">
                                <input class="btn teal" value="Search" type="submit" />
                                <input class="btn red" value="Clear Search" type="button" id="clear-search" />
                            </div>
                          </div>
                    </form>
                    <table>
                        <thead>
                          <tr>
                              <th>Username</th>
                              <th>Plan</th>
                              <th>Subscription Date</th>
                              <th>Is Paid</th>
                              <th>Fees</th>
                              <th>Details</th>
                          </tr>
                        </thead>
                
                        <tbody>
                            {% for each_subscription in subscriptions %}
                            <tr>
                                <td>{{ each_subscription.user_id.email }}</td>
                                <td>{{ each_subscription.plan_id.name }}</td>
                                <td>{{ each_subscription.subscription_date }}</td>
                                <td>{{ each_subscription.is_paid }}</td>
                                <td>RS {{ each_subscription.plan_id.fees }}</td>
                                <td>
                                    <a href="{% url 'core:subscription-detail' each_subscription.id %}" class="btn teal">Detail</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'partials/footer.html' %} {% endblock %}

templates/core/user_plan_detail.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %} GymManagement System - Subscription Detail {% endblock %}
{% block content %}
{%include 'partials/header.html' %}

<div class="blue lighten-5">
    <div class="section">
        <!--   Icon Section   -->
        <div class="row">
            <div class="col s6 center-align">
                <div class="card">
                    <div class="card-image">
                        <img src="{{ subscription.user_id.profile_image.url }}">
                        <span class="card-title">{{ subscription.user_id.email }}</span>
                    </div>
                </div>
            </div>
            <div class="col s6 center-align">
                <div class="card">
                    <div class="card-image">
                        <img src="{{ subscription.plan_id.image.url }}">
                        <span class="card-title">{{ subscription.plan_id.name }}</span>
                    </div>
                    <div class="card-content">
                        <p>
                            {{ subscription.plan_id.description }}
                        </p>
                        <p>
                            Enrolled on - {{ subscription.subscription_date }}
                        </p>
                        <p>
                            Program Fees - {{ subscription.plan_id.fees }}
                        </p>
                        <p>
                            Fees Paid - {{ subscription.is_paid }}
                        </p>
                        <p>
                            Plan Active - {{ subscription.is_active }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'partials/footer.html' %} {% endblock %}

templates/index.html
{% extends 'partials/base.html' %} 
{% load static %} {% block title %} GymManagement System {% endblock %} 
{% block content %}

{% include 'partials/header.html' %}

<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br /><br />
      <h1 class="header center teal-text text-lighten-2">Parallax Template</h1>
      <div class="row center">
        <h5 class="header col s12 light">
          A modern responsive front-end framework based on Material Design
        </h5>
      </div>
      <div class="row center">
        <a
          href="http://materializecss.com/getting-started.html"
          id="download-button"
          class="btn-large waves-effect waves-light teal lighten-1"
          >Get Started</a
        >
      </div>
      <br /><br />
    </div>
  </div>
  <div class="parallax">
    <img src="{% static 'img/background1.jpg' %}" alt="Unsplashed background img 1" />
  </div>
</div>

<div class="container">
  <div class="section">
    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text">
            <i class="material-icons">flash_on</i>
          </h2>
          <h5 class="center">Speeds up development</h5>

          <p class="light">
            We did most of the heavy lifting for you to provide a default
            stylings that incorporate our custom components. Additionally, we
            refined animations and transitions to provide a smoother experience
            for developers.
          </p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">group</i></h2>
          <h5 class="center">User Experience Focused</h5>

          <p class="light">
            By utilizing elements and principles of Material Design, we were
            able to create a framework that incorporates components and
            animations that provide more feedback to users. Additionally, a
            single underlying responsive system across all platforms allow for a
            more unified user experience.
          </p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text">
            <i class="material-icons">settings</i>
          </h2>
          <h5 class="center">Easy to work with</h5>

          <p class="light">
            We have provided detailed documentation as well as specific code
            examples to help new users get started. We are also always open to
            feedback and can answer any questions a user may have about
            Materialize.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light">
          A modern responsive front-end framework based on Material Design
        </h5>
      </div>
    </div>
  </div>
  <div class="parallax">
    <img src="{% static 'img/background2.jpg' %}" alt="Unsplashed background img 2" />
  </div>
</div>

<div class="container">
  <div class="section">
    <div class="row">
      <div class="col s12 center">
        <h3><i class="mdi-content-send brown-text"></i></h3>
        <h4>Contact Us</h4>
        <p class="left-align light">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam
          scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu,
          non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas
          eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem
          neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam
          eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla
          imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac,
          gravida ultrices erat. Nullam eget dignissim mauris, non tristique
          erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
          posuere cubilia Curae;
        </p>
      </div>
    </div>
  </div>
</div>

<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light">
          A modern responsive front-end framework based on Material Design
        </h5>
      </div>
    </div>
  </div>
  <div class="parallax">
    <img src="{% static 'img/background3.jpg' %}" alt="Unsplashed background img 3" />
  </div>
</div>

{% include 'partials/footer.html' %} {% endblock %}

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Gym Management System{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
     <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Nunito&family=PT+Sans&family=Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
</head>
<body>
{% block content %}

{% endblock %}
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/init.js' %}"></script>

<script>
    $(document).ready(function () {

      $('#clear-search').click(() => {
        console.log('Clear search clickde..')
        window.location = window.location.pathname;
      })
      // Init Slider
      $('.slider').slider({
        indicators: false,
        height: 500,
        transition: 500,
        interval: 6000
      });
  
      // Autocomplete
      $('.autocomplete').autocomplete({
        data: {
          "Aruba": null,
          "Cancun Mexico": null,
          "Hawaii": null,
          "Florida": null,
          "California": null,
          "Jamaica": null,
          "Europe": null,
          "The Bahamas": null,
        }
      });
  
      // Init Scrollspy
      $('.scrollspy').scrollSpy();
  
    });
  </script>
</body>

</html>

templates/partials/footer.html
<footer class="section red darken-2 white-text center">
  <p class="flow-text">Gym Membership - Square Fitness Club &copy; 2022</p>
</footer>

templates/partials/header.html
<nav class="white" role="navigation">
    <div class="nav-wrapper container">
        <a id="logo-container" href="#" class="brand-logo">A Square Fitness</a>
        <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'core:list-plans' %}">Plans</a></li>
            <li><a href="{% url 'core:list-users' %}">Users</a></li>
            <li><a href="{% url 'core:list-equipments' %}">Equipments</a></li>
            <li><a href="{% url 'core:list-subscriptions' %}">Subscriptions</a></li>
        </ul>

        <ul id="nav-mobile" class="sidenav">
            <li><a href="{% url 'core:list-plans' %}">Plans</a></li>
            <li><a href="{% url 'core:list-users' %}">Users</a></li>
            <li><a href="{% url 'core:list-equipments' %}">Equipments</a></li>
            <li><a href="{% url 'core:list-subscriptions' %}">Subscriptions</a></li>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
</nav>